repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0 # Última versão estável compatível
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["check"]

      - id: ruff-format
        name: ruff (format)
